######################################################################
# Automatically generated by qmake (3.1) Sun Apr 6 18:51:19 2025
######################################################################

TEMPLATE = app
TARGET = cursorTool
INCLUDEPATH += . 
INCLUDEPATH += $$PWD/dll

# 添加Qt网络模块支持
QT += core gui

# 添加数据库支持
QT += sql

# 版本检查
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

# The following define makes your compiler warn you if you use any
# feature of Qt which has been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += cursorapi.h \
           curlhttpclient.h \
           cursordata.h \
           cursordatareader.h \
           databasemanager.h \
           logmanager.h \
           macrunner.h \
           mainwindow.h \
           powershellrunner.h
FORMS += mainwindow.ui
SOURCES += cursorapi.cpp \
           curlhttpclient.cpp \
           cursordatareader.cpp \
           databasemanager.cpp \
           logmanager.cpp \
           macrunner.cpp \
           main.cpp \
           mainwindow.cpp \
           powershellrunner.cpp
RESOURCES += resources/images.qrc resources/resources.qrc resources/scripts.qrc

CONFIG += c++11

# 默认规则使得在Debug模式下生成带有调试信息的程序
CONFIG(debug, debug|release) {
    DESTDIR = ./debug
    OBJECTS_DIR = ./debug/.obj
    MOC_DIR = ./debug/.moc
    RCC_DIR = ./debug/.rcc
    UI_DIR = ./debug/.ui
} else {
    DESTDIR = ./release
    OBJECTS_DIR = ./release/.obj
    MOC_DIR = ./release/.moc
    RCC_DIR = ./release/.rcc
    UI_DIR = ./release/.ui
}

# RC文件定义程序图标
RC_FILE = cursorTool_resource.rc

# 程序版本信息
VERSION = 1.0.0

# 为DLL添加路径参数 -- 防止DLL加载失败
QMAKE_LFLAGS += -Wl,--enable-runtime-pseudo-reloc

# Optional: 设置程序的元数据
QMAKE_TARGET_COMPANY = "Cursor Pool"
QMAKE_TARGET_PRODUCT = "Cursor Tool"
QMAKE_TARGET_DESCRIPTION = "Cursor API Tool"
QMAKE_TARGET_COPYRIGHT = "Copyright (C) 2023"

# Windows资源文件中的应用图标
RC_ICONS = resources/icon.ico

# 库文件目录和链接库
LIBS += -L$$PWD/dll -llibcurl-x64
# 在 .pro 文件中添加
# Windows specific settings
win32 {
    # RC_FILE = cursor.rc  # 注释掉这行，让Qt自动处理图标
    # 设置应用程序图标（使用相对路径，Qt会正确解析）
    RC_ICONS = $$PWD/resources/images/cursor_logo.ico
}

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target
